# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstallationsSnippets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseInstallations'

  target 'InstallationsSnippetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
