# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/MLVision'
pod 'Firebase/MLVisionAutoML'

target 'objc-snippets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for objc-snippets

end

target 'swift-snippets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-snippets

end
