# Podfile left around for legacy snippets. The project has since been migrated to SPM.
platform :ios, '12.0'
use_frameworks!

# [START pod_firebase_storage]
pod 'FirebaseStorage', '~> 9.0'
# [END pod_firebase_storage]
# [START pod_firebaseui_storage]
pod 'FirebaseStorageUI'
# [END pod_firebaseui_storage]

target 'StorageReference' do
end
target 'StorageReferenceSwift' do
end

