# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLFunctionsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Functions'

end

target 'MLFunctionsExampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Functions'

end
