platform :ios, '9.0'

target 'InvitesSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/DynamicLinks'

  target 'InvitesSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InvitesSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'InvitesSampleObjC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/DynamicLinks'

end
