# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'firestore-smoketest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firestore-smoketest
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # [START geofire_pod]
  pod 'GeoFire/Utils'
  # [END geofire_pod]

  target 'firestore-smoketestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firestore-smoketestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
