on: 
  pull_request:
    paths:
      - 'firestore/**'
      - '.github/workflows/firestore.yml'
name: Firestore
jobs:
  swift-build:
    name: Swift build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 16']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install deps
        run: brew install xcbeautify
      - name: Build Swift snippets
        run: |
          cp .github/GoogleService-Info-CI.plist firestore/swift/firestore-smoketest/GoogleService-Info.plist
          cd firestore/swift
          xcodebuild -project firestore-smoketest.xcodeproj clean build -scheme firestore-smoketest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify --renderer github-actions
        env: 
         destination: ${{ matrix.destination }}
  objc-build:
    name: ObjC build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 16']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install deps
        run: brew install xcbeautify
      - name: Build ObjC snippets
        run: |
          cp .github/GoogleService-Info-CI.plist firestore/objc/GoogleService-Info.plist
          cd firestore/objc
          xcodebuild -project firestore-smoketest-objc.xcodeproj clean build -scheme firestore-smoketest-objc -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify --renderer github-actions
        env: 
         destination: ${{ matrix.destination }}
