on: 
  pull_request:
    paths:
      - 'installations/**'
      - '.github/workflows/installations.yml'
name: Installations
jobs:
  swift-build:
    name: Swift build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 16']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install deps
        run: brew install xcbeautify
      - name: Build Swift snippets
        run: |
          cd installations/
          xcodebuild -project InstallationsSnippets.xcodeproj clean build -scheme InstallationsSnippets -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify --renderer github-actions
        env: 
         destination: ${{ matrix.destination }}