on: 
  pull_request:
    paths:
      - 'installations/**'
      - '.github/workflows/installations.yml'
name: Installations
jobs:
  swift-build:
    name: Swift build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Swift snippets
        run: |
          cd installations/
          pod install --repo-update
          xcodebuild -workspace InstallationsSnippets.xcworkspace clean build -scheme InstallationsSnippets -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env: 
         destination: ${{ matrix.destination }}