on: 
  pull_request:
    paths:
      - 'storage/**'
      - '.github/workflows/storage.yml'
name: Storage
jobs:
  swift-build:
    name: Swift build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 16']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Swift snippets
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.1.app/Contents/Developer
          cd storage
          xcodebuild -project StorageReference.xcodeproj clean build -scheme StorageReferenceSwift -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env: 
         destination: ${{ matrix.destination }}
  objc-build:
    name: ObjC build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPhone 16']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build ObjC snippets
        run: |
          cd storage
          xcodebuild -project StorageReference.xcodeproj clean build -scheme StorageReference -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env: 
         destination: ${{ matrix.destination }}
